### PR TITLE
Docs etc

### PR DESCRIPTION
**Pull request by aawdls**
Here are some minor updates to the documentation, to try to make it clear for somebody who is less familiar with the context.

I have also fleshed out the instructions for setting up the environment for the virtac.

I'm working towards making an atip release; there are some minor code changes needed as well to make it work with the latest pyat.

### CODE REVIEW

**Comment by aawdls** [comment]
Barring a bit more testing I think this is pretty much ready to go

**Comment by aawdls** [comment]
@T-Nicholls do you have any objection to me adding cothread in the install_requires? We import it in simulator.py.so I think it's a hard requirement

**Comment by T-Nicholls** [comment]
When you add cothread to the intsall_requires, can you also please add a debugging section to `INSTALL.rst`, something like:

> For problems with your pyAT installation please refer to `at/pyat/README.rst`.
> N.B. for ATIP to function with Python 3.7 or later, please ensure you use Cothread>=2.16.

Perhaps also a line for Pytac?
Once you're happy the docs build correctly on RTD then I think this can be merged, unless it needs input from Will.

**Comment by aawdls** [comment]
Done.
Readthedocs looks fine. I don't think we need to wait for Will.

**Comment by aawdls** [comment]
I've moved the `rings` directory inside the `atip` directory. Otherwise, it gets installed in `site-packages` as a separate "package" directory. This didn't seem to make sense to me as it's part of atip. I think I have caught all the references to the path... Are you OK with this?

**Comment by T-Nicholls** [comment]
The rings were originally separate as I was unsure if we would include them in a release and there was no reason for them to be in the `atip` directory. So moving them now seems like a sensible change.
Out of interest what is the purpose of building wheels on Travis in this way? Are we able to retrieve them? Should we implement automatic wheel building and upload like we did for AT?

**Comment by aawdls** [comment]
All I had in mind was a simple "build succeeds" check, as I found it could fail e.g. if I put stuff in the wrong section of the `setup.cfg`. It would be nice to set up something like what you have done for AT with continuous delivery, but maybe as a future improvement. We could chat about this some time.

**Comment by T-Nicholls** [comment]
Ok; yes, perhaps we could ask Will's opinion on it when he returns.
Let's merge this if you're happy.

**Comment by aawdls** [comment]
Cool, done.
(btw, maybe something like this would allow us to upload to test-pypi without needing another service https://docs.travis-ci.com/user/deployment/pypi/ )

**Pull request merged**
