### PR TITLE
Repository restructure

### PR DESCRIPTION
**Pull request by willrogers**
Drop Python 2. Add CI using Github Actions.

Format with Black.

### CODE REVIEW

**Review by MJGaughran — DISMISSED** [review]

**Review by MJGaughran — APPROVED** [review]
While there's nothing wrong with this pull request, you are missing a couple of useful things from the Diamond template for Python 3 modules:

- Scripts in the Pipfile (tests, docs, etc) for use by CI
- Standard configuration for flake8, mypy etc in setup.cfg. It is also affected by the list of modules in the Pipfile

I also rename test to tests. It's the standard for pytest, rather than unittest.

**Comment by willrogers** [comment]
> It is also affected by the list of modules in the Pipfile

What does this mean?

**Comment by MJGaughran** [comment]
In all honesty, I never figured it out entirely. I just stick to the list of modules provided by the Python 3 template.

I'm not sure whether flake8-isort, for instance, has any effect without the corresponding configuration file.

**Comment by willrogers** [comment]
I have moved the test directory and added a script entry in Pipfile.

**Pull request merged**
