### PR TITLE
Move configuration to setup.cfg.

### PR DESCRIPTION
**Pull request by willrogers**
@T-Nicholls here's the configuration change.

### CODE REVIEW

**Comment by T-Nicholls** [comment]
Ooh, I was not aware of this. can we do this for Pytac too?

**Comment by willrogers** [comment]
Yes, that's the plan.

**Comment by willrogers** [comment]
Thinking about it, this mechanism doesn't work with the old version of setuptools that we use on RHEL6. So I might hold off until we get to python 3 on RHEL7, as I will probably want to make a 0.3.0 release of Pytac available on RHEL6.

**Comment by aawdls** [comment]
Can we safely merge this now that python3 is pretty much here?

Interestingly I did do a RHEL6 release of pytac 0.3.0 so I wonder if I missed something

**Pull request merged**
